//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-26 11:16:36 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using CL.Enum.Common;
using CL.SystemInfo.DAL;
using CL.SystemInfo.Entity;

namespace CL.SystemInfo.BLL
{

    /// <summary>
    ///ErrorLog info
    /// </summary>
    public class ErrorLogBLL
    {
        ErrorLogDAL dal = new ErrorLogDAL(DbConnectionEnum.CaileSystem);

        /// <summary>
        /// 插入错误日志
        /// </summary>
        /// <param name="entity">错误日志对象</param>
        /// <returns></returns>
        public int InsertEntity(ErrorLogEntity entity)
        {
            return dal.InsertEntity(entity);
        }
    }
}
