//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-26 11:16:36 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using CL.Enum.Common;
using CL.SystemInfo.DAL;
using CL.SystemInfo.Entity;
using System.Collections.Generic;

namespace CL.SystemInfo.BLL
{

    /// <summary>
    ///ManagerLog info
    /// </summary>
    public class ManagerLogBLL
    {
        ManagerLogDAL dal = new ManagerLogDAL(DbConnectionEnum.CaileSystem);


        /// <summary>
        /// 插入对象
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public int InsertEntity(ManagerLogEntity entity)
        {
            return dal.InsertEntity(entity);
        }
        /// <summary>
        /// 根据用户名返回上一次登录记录
        /// </summary>
        public ManagerLogEntity QueryEntity(string UserName, int top_num, string ActionType)
        {
            return dal.QueryEntity(UserName, top_num, ActionType);
        }
        /// <summary>
        /// 删除N天前的日志数据
        /// </summary>
        public int DeletedDay(int dayCount)
        {
            return dal.DeletedDay(dayCount);

        }
        /// <summary>
        /// 分页获取数据列表
        /// </summary>
        public List<ManagerLogEntity> QueryListByPage(string strName, string orderby, int pageSize, int pageIndex, ref int recordCount)
        {
            return dal.QueryListByPage(strName, orderby, pageSize, pageIndex, ref recordCount);
        }
    }
}
