//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-26 11:16:37 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using CL.Enum.Common;
using CL.SystemInfo.DAL;
using CL.SystemInfo.Entity;

namespace CL.SystemInfo.BLL
{

    /// <summary>
    ///RosleValue info
    /// </summary>
    public class RosleValueBLL
    {
        RosleValueDAL dal = new RosleValueDAL(DbConnectionEnum.CaileSystem);


        /// <summary>
        /// 更新权限
        /// </summary>
        /// <param name="RoleID"></param>
        /// <param name="Entitys"></param>
        /// <returns></returns>
        public bool ModifyRoles(int RoleID, List<RosleValueEntity> Entitys)
        {
            return dal.ModifyRoles(RoleID, Entitys);
        }



    }
}
