//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-26 11:36:00 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using CL.Enum.Common;
using CL.Game.DAL;
using CL.Game.Entity;
using CL.View.Entity.Game;
using System.Collections.Generic;

namespace CL.Game.BLL
{

    /// <summary>
    ///ChaseTasks info
    /// </summary>
    public class ChaseTasksBLL
    {
        ChaseTasksDAL dal = new ChaseTasksDAL(DbConnectionEnum.CaileGame);

        /// <summary>
        /// 是否存在该记录
        /// </summary>
        public bool Exists(int ID)
        {
            return dal.Exists(ID);
        }
        /// <summary>
        /// 获取方案统计数据实体
        /// </summary>
        public udv_ChaseTasks QueryChaseTaskTotal(int ChaseTaskID)
        {
            return dal.QueryChaseTaskTotal(ChaseTaskID);
        }
        /// <summary>
        /// 获取方案数据明细
        /// </summary>
        public List<udv_ChaseTasksDetails> QueryChaseTaskDetails(long ChaseTaskID)
        {

            return dal.QueryChaseTaskDetails(ChaseTaskID);
        }
        /// <summary>
        /// 撤销单期追号
        /// 待优化方法
        /// </summary>
        /// <param name="ChaseTaskDetailsID"></param>
        /// <param name="IsSystem"></param>
        /// <param name="ReturnDescription"></param>
        /// <returns></returns>
        public int QuashChaseTaskDetail(int ChaseTaskDetailsID, bool IsSystem, ref string ReturnDescription)
        {
            return dal.QuashChaseTaskDetail(ChaseTaskDetailsID, IsSystem, ref ReturnDescription);
        }
        /// <summary>
        /// 撤消总追号任务
        /// </summary>
        /// <param name="ChaseTaskDetailsID"></param>
        /// <param name="IsSystem"></param>
        /// <param name="ReturnDescription"></param>
        /// <returns></returns>
        public int QuashChaseTask(int ChaseTaskID, bool IsSystem, ref string ReturnDescription)
        {
            return dal.QuashChaseTask(ChaseTaskID, IsSystem, ref ReturnDescription);
        }
        /// <summary>
        /// 根据方案编号查询追号对象
        /// </summary>
        /// <param name="SchemeID"></param>
        /// <returns></returns>
        public ChaseTasksEntity QueryEntityBySchemeID(long SchemeID)
        {
            return dal.QueryEntityBySchemeID(SchemeID);
        }
    }
}
