//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-26 11:36:00 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using CL.Enum.Common;
using CL.Game.DAL;
using CL.Game.Entity;
using System.Collections.Generic;

namespace CL.Game.BLL
{

    /// <summary>
    ///SchemesDetail info
    /// </summary>
    public class SchemesDetailBLL
    {
        SchemesDetailDAL dal = new SchemesDetailDAL(DbConnectionEnum.CaileGame);
        /// <summary>
        /// 根据方案编号查询方案详情
        /// </summary>
        /// <param name="SchemeID"></param>
        /// <returns></returns>
        public List<SchemesDetailEntity> QueryEntityBySchemeID(long SchemeID)
        {
            return dal.QueryEntityBySchemeID(SchemeID);
        }
        /// <summary>
        /// 查询单个对象
        /// </summary>
        /// <param name="SDID"></param>
        /// <returns></returns>
        public SchemesDetailEntity QueryEntity(long SDID)
        {
            return dal.QueryEntity(SDID);
        }
    }
}
