//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-26 11:36:00 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using CL.Enum.Common;
using CL.Game.DAL;
using CL.Game.Entity;
using CL.Redis.BLL;
using System;
using System.Collections.Generic;

namespace CL.Game.BLL
{

    /// <summary>
    ///SystemSetInfo info
    /// </summary>
    public class SystemSetInfoBLL
    {
        SystemSetInfoDAL dal = new SystemSetInfoDAL(DbConnectionEnum.CaileGame);
        
        /// <summary>
        /// 查询对象
        /// </summary>
        /// <param name="SetKey"></param>
        /// <returns></returns>
        public SystemSetInfoEntity QueryEntity(string SetKey)
        {
            return dal.QueryEntity(SetKey);
        }
        /// <summary>
        /// 修改对象
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public int ModifyEntity(SystemSetInfoEntity entity)
        {
            return dal.ModifyEntity(entity);
        }
        /// <summary>
        /// 获取实体集合
        /// </summary>
        public List<SystemSetInfoEntity> QueryEntitys()
        {
            return dal.QueryEntitys();
        }
    }
}
