//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-26 11:36:01 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using CL.Enum.Common;
using CL.Game.DAL;

namespace  CL.Game.BLL
{    

	/// <summary>
    ///UsersStaticdata info
    /// </summary>
    public class UsersStaticdataBLL
    {
		UsersStaticdataDAL dal = new UsersStaticdataDAL(DbConnectionEnum.CaileGame);
         
	 }
}
	