//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-08 15:26:14 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;

namespace CL.Game.Entity
{

    /// <summary>
    /// 活动主表
    /// </summary>
    [Table("CT_Activity")]
    public class ActivityEntity
    {

        /// <summary>
        /// 活动标识
        /// </summary>
        [Key]
        public int ActivityID { get; set; }

        /// <summary>
        /// 活动类型：0 官方活动，1 彩乐平台活动
        /// </summary>
        public int ActivityType { get; set; }

        /// <summary>
        /// 活动主题
        /// </summary>
        public string ActivitySubject { get; set; }

        /// <summary>
        /// 活动描述
        /// </summary>
        public string ActivityDescribe { get; set; }

        /// <summary>
        /// 活动创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 活动开始时间
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 活动结束时间
        /// </summary>
        public DateTime EndTime { get; set; }

        /// <summary>
        /// 活动变更时间
        /// </summary>
        public DateTime? ModifyTime { get; set; }

        /// <summary>
        /// 活动变更描述
        /// </summary>
        public string ModifyDescribe { get; set; }

        /// <summary>
        /// 活动金额
        /// </summary>
        public long ActivityMoney { get; set; }

        /// <summary>
        /// 活动变更金额
        /// </summary>
        public long? ModifyMoney { get; set; }

        /// <summary>
        /// 是否变更活动信息
        /// </summary>
        public bool IsModify { get; set; }

        /// <summary>
        /// 活动申请状态：0 申请中，1 审核通过，2 审核拒绝
        /// </summary>
        public int ActivityApply { get; set; }

        /// <summary>
        /// 币种单位(彩乐平台币种)：0 人民币(余额)，1 元宝，2 游戏币
        /// </summary>
        public byte CurrencyUnit { get; set; }

        /// <summary>
        /// 落地页面
        /// </summary>
        public string LandingPage { set; get; }

        /// <summary>
        /// 广告地址
        /// </summary>
        public string ADUrl { set; get; }
    }
}
