//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///ChaseTaskDetails info
    /// </summary>
    [Table("CT_ChaseTaskDetails")]
    public class ChaseTaskDetailsEntity
    {

        /// <summary>
        /// 追号明细流水号
        /// </summary>
        [Key]
        public long ID { get; set; }

        /// <summary>
        /// 追号任务编号
        /// </summary>
        public long ChaseTaskID { get; set; }

        /// <summary>
        /// 方案订单编号
        /// </summary>
        public long SchemeID { get; set; }

        /// <summary>
        /// 任务发起时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 期号
        /// </summary>
        public long IsuseID { get; set; }

        /// <summary>
        /// 倍数
        /// </summary>
        public int Multiple { get; set; }

        /// <summary>
        /// 本期追号金额
        /// </summary>
        public long Amount { get; set; }

        /// <summary>
        /// 追号使用彩券编号
        /// </summary>
        public string RedPacketId { get; set; }

        /// <summary>
        /// 使用彩券支付的金额
        /// </summary>
        public decimal RedPacketMoney { get; set; }

        /// <summary>
        /// 撤销状态:0 未撤销 1 用户撤销 2 系统撤销
        /// </summary>
        public short QuashStatus { get; set; }

        /// <summary>
        /// 是否执行
        /// </summary>
        public bool IsExecuted { get; set; }

        /// <summary>
        /// 保密级别：0 不保密 1 到截止 2 到开奖 3 永远
        /// </summary>
        public short SecrecyLevel { get; set; }

        /// <summary>
        /// 投注号码
        /// </summary>
        public string LotteryNumber { get; set; }

        /// <summary>
        /// 是否分享
        /// </summary>
        public byte IsShare { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public bool? IsSendOut { get; set; }

    }
}
