//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///ChaseTasks info
    /// </summary>
    [Table("CT_ChaseTasks")]
    public class ChaseTasksEntity
    {

        /// <summary>
        /// 追号任务流水号
        /// </summary>
        [Key]
        public long ChaseTaskID { get; set; }

        /// <summary>
        /// 发起人编号
        /// </summary>
        public long UserID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public long SchemeID { get; set; }

        /// <summary>
        /// 彩种编码
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 开始时间
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 结束时间
        /// </summary>
        public DateTime EndTime { get; set; }

        /// <summary>
        /// 任务发起时间
        /// </summary>
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 定制期数
        /// </summary>
        public int IsuseCount { get; set; }

        /// <summary>
        /// 投注方式（1.机选  2.自选）
        /// </summary>
        public short BetType { get; set; }

        /// <summary>
        /// 终止条件（1.全部方案  2.一等奖或二等奖   3.三等奖以上）
        /// </summary>
        public short StopTypeWhenWin { get; set; }

        /// <summary>
        /// 终止金额
        /// </summary>
        public long StopTypeWhenWinMoney { get; set; }

        /// <summary>
        /// 撤销状态:0 未撤销 1 用户撤销 2 系统撤销
        /// </summary>
        public short QuashStatus { get; set; }

        /// <summary>
        /// 任务标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public string Descriptions { get; set; }

        /// <summary>
        /// 佣金比例
        /// </summary>
        public double SchemeBonusScale { get; set; }

        /// <summary>
        /// 追号来源：追号任务来自的客户端，1表示来自网页，2表示来自手机应用
        /// </summary>
        public int FromClient { get; set; }

    }
}
