//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///Isuses info
    /// </summary>
    [Table("CT_Isuses")]
    public class IsusesEntity
    {

        /// <summary>
        /// 
        /// </summary>
        [Key]
        public long IsuseID { get; set; }

        /// <summary>
        /// 彩种编号
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 期号名
        /// </summary>
        public string IsuseName { get; set; }

        /// <summary>
        /// 开始时间
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 截止时间
        /// </summary>
        public DateTime EndTime { get; set; }

        /// <summary>
        /// 追号任务是否执行了
        /// </summary>
        public bool IsExecuteChase { get; set; }

        /// <summary>
        /// 是否开奖了
        /// </summary>
        public bool IsOpened { get; set; }

        /// <summary>
        /// 开奖号码
        /// </summary>
        public string OpenNumber { get; set; }

        /// <summary>
        /// 开奖操作员ID
        /// </summary>
        public int OpenOperatorID { get; set; }

        /// <summary>
        /// 奖期状态：0 未开启 1 开始 2 暂停 3 截止 4 期结 5 返奖 6 返奖结束
        /// </summary>
        public byte IsuseState { get; set; }

        /// <summary>
        /// 奖期状态的更新时间
        /// </summary>
        public DateTime UpdateTime { get; set; }

        /// <summary>
        /// 开奖公告
        /// </summary>
        public string OpenNotice { get; set; }

        /// <summary>
        /// 销售总额
        /// </summary>
        public long TotalSales { get; set; }

        /// <summary>
        /// 开奖时间
        /// </summary>
        public DateTime? OpenTime { get; set; }

        /// <summary>
        /// 滚存：滚入下期
        /// </summary>
        public string WinRollover { get; set; }

        /// <summary>
        /// 投注提示
        /// </summary>
        public string BettingPrompt { get; set; }

    }
}
