//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///Lotteries info
    /// </summary>
    [Table("CT_Lotteries")]
    public class LotteriesEntity
    {

        /// <summary>
        /// 彩种流水号
        /// </summary>
        [Key]
        public int LotteryID { get; set; }

        /// <summary>
        /// 彩种编码规则，采取三位编码，具体如下：类型一、10分钟一期的（新快三101，江西快三102，重庆时时彩121   类型二、五分钟一期的（快乐扑克201 ）  类型三、隔天开奖的（双色球801，大乐透901}
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 彩种名称
        /// </summary>
        public string LotteryName { get; set; }

        /// <summary>
        /// 彩种拼音简写
        /// </summary>
        public string Shorthand { get; set; }

        /// <summary>
        /// 副标题，相当于小广告，如“两元博五百万”
        /// </summary>
        public string Subhead { get; set; }

        /// <summary>
        /// 最大追号期数 (如： '10:期' 表示能向后追10期 '1:天' 表示高频玩法能追1天内所有期)
        /// </summary>
        public string MaxChaseIsuse { get; set; }

        /// <summary>
        /// 排序号
        /// </summary>
        public int? Sort { get; set; }

        /// <summary>
        /// 彩票类型：1.福彩 2.体彩 3.足彩 4.高频彩
        /// </summary>
        public byte? TypeID { get; set; }

        /// <summary>
        /// 开奖号码格式  如果有括号代表可能有特别号码（如·14年双色球增加的幸运蓝球）
        /// </summary>
        public string WinNumberExemple { get; set; }

        /// <summary>
        /// 开奖周期规则，10分，5分，[2,4,7]，[1,3,6]
        /// </summary>
        public string IntervalType { get; set; }

        /// <summary>
        /// 出票方式(0 - 本地出票 1 - 华阳电子票)
        /// </summary>
        public short? PrintOutType { get; set; }

        /// <summary>
        /// 单注金额，分
        /// </summary>
        public int? Price { get; set; }

        /// <summary>
        /// 能投注的最大倍数
        /// </summary>
        public int? MaxMultiple { get; set; }

        /// <summary>
        /// 截止投注时间，单位 秒
        /// </summary>
        public int? OffTime { get; set; }

        /// <summary>
        /// 追号延迟执行间隔时间，秒
        /// </summary>
        public int? ChaseDeferTime { get; set; }

        /// <summary>
        /// 撤销追号提前时间间隔，秒
        /// </summary>
        public int? QuashChaseTime { get; set; }

        /// <summary>
        /// 彩种介绍
        /// </summary>
        public string Kinformation { get; set; }

        /// <summary>
        /// 是否重点推荐
        /// </summary>
        public bool? IsEmphasis { get; set; }

        /// <summary>
        /// 游戏版本号
        /// </summary>
        public int? ModuleVersion { get; set; }

        /// <summary>
        /// 是否加奖
        /// </summary>
        public bool IsAddaward { get; set; }

        /// <summary>
        /// 是否启用
        /// </summary>
        public bool IsEnable { get; set; }

        /// <summary>
        /// 彩种停止销售原因
        /// </summary>
        public string StopReason { get; set; }

        /// <summary>
        /// 是否停止销售
        /// </summary>
        public bool? IsStop { get; set; }

        /// <summary>
        /// 是否热门彩种
        /// </summary>
        public bool? IsHot { get; set; }

        /// <summary>
        /// 期号提前结束时间
        /// </summary>
        public int? AdvanceEndTime { get; set; }

        /// <summary>
        /// 预售时间
        /// </summary>
        public int? PresellTime { get; set; }
        /// <summary>
        /// 群组编号
        /// </summary>
        public string ChatGroups { set; get; }
        /// <summary>
        /// 聊天室编号
        /// </summary>
        public string ChatRooms { set; get; }

    }
}
