//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///News info
    /// </summary>
    [Table("CT_News")]
    public class NewsEntity
    {

        /// <summary>
        /// 站点ID
        /// </summary>
        [Key]
        public int NewsID { get; set; }

        /// <summary>
        /// 资讯栏目ID T_NewsTypes的ID
        /// </summary>
        public int TypeID { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        public string Title { set; get; }

        /// <summary>
        /// 关键字
        /// </summary>
        public string Keys { set; get; }

        /// <summary>
        /// 富文本
        /// </summary>
        public string RichText { set; get; }

        /// <summary>
        /// 纯文本
        /// </summary>
        public string PlainText { set; get; }

        /// <summary>
        /// 彩种
        /// </summary>
        public int LotteryCode { set; get; }

        /// <summary>
        /// 作者
        /// </summary>
        public string Author { set; get; }

        /// <summary>
        /// 来源
        /// </summary>
        public string Source { set; get; }

        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { set; get; } = 0;

        /// <summary>
        /// 是否推荐
        /// </summary>
        public bool IsRecommend { set; get; }

        /// <summary>
        /// 显示设备：1.全部 2.网站 3.客户端
        /// </summary>
        public int Equipment { set; get; }

        /// <summary>
        /// 发布人ＩＤ
        /// </summary>
        public long PublishID { set; get; }

        /// <summary>
        /// 发布人
        /// </summary>
        public string Publish { set; get; }

        /// <summary>
        /// 发布时间
        /// </summary>
        public DateTime PublishTime { set; get; }

        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime? ModifyTime { set; get; }

        /// <summary>
        /// 更新人
        /// </summary>
        public string Modify { set; get; } = string.Empty;

        /// <summary>
        /// 更新人ID
        /// </summary>
        public long ModifyID { set; get; } = 0;

        /// <summary>
        /// 审核人ID
        /// </summary>
        public long AuditingID { set; get; } = 0;

        /// <summary>
        /// 审核人
        /// </summary>
        public string Auditing { set; get; } = string.Empty;

        /// <summary>
        /// 审核时间
        /// </summary>
        public DateTime? AuditingTime { set; get; }

        /// <summary>
        /// 阅读数
        /// </summary>
        public int ReadNum { set; get; } = 0;

        /// <summary>
        /// 支持数
        /// </summary>
        public int SupportNum { set; get; } = 0;

        /// <summary>
        /// 反对数
        /// </summary>
        public int OpposeNum { set; get; } = 0;

        /// <summary>
        /// 审核状态：1.待审核 2.审核通过 3.审核未通过
        /// </summary>
        public int AuditingStatus { set; get; } = 1;

        /// <summary>
        /// 是否删除 
        /// </summary>
        public bool IsDel { set; get; } = false;

        /// <summary>
        /// 推荐投注号码
        /// </summary>
        public string LotNumber { set; get; }


    }
    public class udv_NewsTypeName : NewsEntity
    {
        /// <summary>
        /// 类型名称
        /// </summary>
        public string TypeName { set; get; }
    }
}
