//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-11 15:43:13 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///OutETickets info
    /// </summary>
    [Table("CT_OutETickets")]
    public class OutETicketsEntity
    {

        /// <summary>
        /// 出票明细主键
        /// </summary>
        [Key]
        public long OutETicketsID { get; set; }

        /// <summary>
        /// 出票商户， 1：华阳
        /// </summary>
        public int MerchantCode { get; set; }
        /// <summary>
        /// 玩法编号 规则，采取五位编码，三位彩种编号+两位序号，具体如下：新快三和值3,10101  新快三和值4,10102  新快三三同号,10117双色球机选一注,80101
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 商户票号
        /// </summary>
        public string MerchantTicket { get; set; }

        /// <summary>
        /// 华阳票号
        /// </summary>
        public string HuaYangTicket { get; set; }

        /// <summary>
        /// 金额
        /// </summary>
        public long Money { get; set; }

        /// <summary>
        /// 投注倍数
        /// </summary>
        public int Multiple { get; set; }

        /// <summary>
        /// 奖金
        /// </summary>
        public long Bonus { get; set; }

        /// <summary>
        /// 送票时间
        /// </summary>
        public DateTime SendTicketDateTime { get; set; }

        /// <summary>
        /// 出票时间
        /// </summary>
        public DateTime OutTicketDateTime { get; set; }

        /// <summary>
        /// 出票状态(1-未出票，2-出票成功，3-出票失败)
        /// </summary>
        public byte OutTicketStauts { get; set; }

    }
}
