//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///PlayTypes info
    /// </summary>
    [Table("CT_PlayTypes")]
    public class PlayTypesEntity
    {

        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public int PlayID { get; set; }

        /// <summary>
        /// 玩法编号 规则，采取五位编码，三位彩种编号+两位序号，具体如下：新快三和值3,10101  新快三和值4,10102  新快三三同号,10117双色球机选一注,80101
        /// </summary>
        public int PlayCode { get; set; }

        /// <summary>
        /// 彩种编号
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 玩法名称
        /// </summary>
        public string PlayName { get; set; }

        /// <summary>
        /// 单注金额
        /// </summary>
        public int Price { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        public string ModuleName { get; set; }

        /// <summary>
        /// 能投注的最大倍数
        /// </summary>
        public int MaxMultiple { get; set; }

        /// <summary>
        /// 排序号
        /// </summary>
        public int Sort { get; set; }

    }
}
