//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-08 15:26:15 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;

namespace CL.Game.Entity
{

    /// <summary>
    /// 投注累计排名加奖
    /// </summary>
    [Table("CT_RegularBetRanking")]
    public class RegularBetRankingEntity
    {

        /// <summary>
        /// 标识列
        /// </summary>
        [Key]
        public int RBetRanID { get; set; }

        /// <summary>
        /// 加奖规则标识
        /// </summary>
        public int RegularID { get; set; }

        /// <summary>
        /// 加奖玩法
        /// </summary>
        public int PlayCode { get; set; }

        /// <summary>
        /// 排名规则：root 顶级节点，item 项目节点，placing 名次(整型)，award 加奖金额(长整型，分为单位)；最大支持前十名或后十名加奖(倒数名称请按负数计算 如：倒数第一名  -1 ， 倒数第二 -2 等等)
        /// 实例 如：
        /// <?xml version = "1.0" encoding="utf-8"?>
        /// <root> 
        ///   <item> 
        ///     <placing>1</placing>  
        ///     <award>20000</award> 
        ///   </item>  
        ///   <item> 
        ///     <placing>2</placing>  
        ///     <award>8000</award> 
        ///   </item> 
        /// </root>
        /// </summary>
        public string BetRanking { get; set; }

    }
}
