//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-08 15:26:15 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;

namespace CL.Game.Entity
{

    /// <summary>
    /// 数字彩中球加奖
    /// </summary>
    [Table("CT_RegularBall")]
    public class RegularBallEntity
    {

        /// <summary>
        /// 标识列
        /// </summary>
        [Key]
        public int RBallID { get; set; }

        /// <summary>
        /// 加奖规则标识
        /// </summary>
        public int RegularID { get; set; }

        /// <summary>
        /// 加奖玩法
        /// </summary>
        public int PlayCode { get; set; }

        /// <summary>
        /// 单次加奖金额
        /// </summary>
        public long AwardMoney { get; set; }

        /// <summary>
        /// 上限金额
        /// </summary>
        public long TopLimit { get; set; }

        /// <summary>
        /// 类型：1 指定红球数字，2 指定蓝球数字(高频彩没有蓝球)
        /// </summary>
        public int BallType { get; set; }

        /// <summary>
        /// 指定选号
        /// </summary>
        public string Ball { get; set; }

    }
}
