//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-08 15:26:15 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
//namespace  Model.Entities
namespace CL.Game.Entity
{

    /// <summary>
    /// 节假日加奖
    /// </summary>
    [Table("CT_RegularHoliday")]
    public class RegularHolidayEntity
    {

        /// <summary>
        /// 标识列
        /// </summary>
        [Key]
        public int RHolidayID { get; set; }

        /// <summary>
        /// 加奖规则标识
        /// </summary>
        public int RegularID { get; set; }

        /// <summary>
        /// 类型：1 周六加奖，2 周日加奖，3 周六日加奖，4 指定时间段加奖(按活动开始结束时间加奖)
        /// </summary>
        public int HolidayType { get; set; }

        /// <summary>
        /// 单次加奖金额
        /// </summary>
        public long AwardMoney { get; set; }

        /// <summary>
        /// 加奖玩法
        /// </summary>
        public int PlayCode { get; set; }

        /// <summary>
        /// 单日上限金额
        /// </summary>
        public long TopLimitDay { get; set; }

    }
}
