//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-08 15:26:15 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;

namespace CL.Game.Entity
{

    /// <summary>
    /// 中奖金额区间加奖
    /// </summary>
    [Table("CT_RegularAwardInterval")]
    public class RegularAwardIntervalEntity
    {

        /// <summary>
        /// 标识列
        /// </summary>
        [Key]
        public int RAwardIntervalID { get; set; }

        /// <summary>
        /// 加奖规则标识
        /// </summary>
        public int RegularID { get; set; }

        /// <summary>
        /// 加奖玩法
        /// </summary>
        public int PlayCode { get; set; }

        /// <summary>
        /// 排名规则：root 顶级节点，item 项目节点，pk 序号(整型)，award 加奖金额(长整型，分为单位)，min 最小金额，max 最大金额(当最大金额为0时，则中奖金额累计大于等于最小金额时即可加奖)；最大支持十个区间加奖
        /// 实例 如：
        /// <?xml version = "1.0" encoding="utf-8"?>
        /// <root> 
        ///    <item> 
        ///         <pk>1</pk>  
        ///         <min>20000</min>  
        ///         <max>0</max>  
        ///         <award>10000</award> 
        ///    </item>  
        ///    <item> 
        ///         <pk>2</pk>  
        ///         <min>10000</min>  
        ///         <max>20000</max>  
        ///         <award>10000</award> 
        ///     </item> 
        /// </root>
        /// </summary>
        public string AwardInterval { get; set; }

    }
}
