//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-05 14:40:45 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///SalePoint info
    /// </summary>
    [Table("CT_SalePoint")]
    public class SalePointEntity
    {

        /// <summary>
        /// 
        /// </summary>
        [Key]
        public long SalePointID { get; set; }

        /// <summary>
        /// 出票平台：0彩乐:1华阳
        /// </summary>
        public int TicketSourceID { get; set; }

        /// <summary>
        /// （这里可能是多个彩票编号的拼接字符串）玩法编号 规则，采取五位编码，三位彩种编号+两位序号，具体如下：新快三和值3,10101  新快三和值4,10102  新快三三同号,10117双色球机选一注,80101
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 彩票编码拼接字符串
        /// </summary>
        public string LotteryName { get; set; }

        /// <summary>
        /// 销售阶梯和返点的拼接字符串
        /// </summary>
        public string SalesRebate { get; set; }

        /// <summary>
        /// 文档签名
        /// </summary>
        public long FileSign { get; set; }

        /// <summary>
        /// 操作员编号
        /// </summary>
        public long OperatorID { get; set; }

        /// <summary>
        /// 操作人名称
        /// </summary>
        public string OperatorName { get; set; }

        /// <summary>
        /// 操作时间
        /// </summary>
        public DateTime OperatorTime { get; set; }

        /// <summary>
        /// 审核人编号
        /// </summary>
        public long? AuditorID { get; set; }

        /// <summary>
        /// 审核人名称
        /// </summary>
        public string AuditorName { get; set; }

        /// <summary>
        /// 审核时间
        /// </summary>
        public DateTime? AuditTime { get; set; }

        /// <summary>
        /// 状态（-2：过期，-1：审核不通过，1：待审核，2：有效）
        /// </summary>
        public byte SalePointStatus { get; set; }

        /// <summary>
        /// 开启时间
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 结束时间
        /// </summary>
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public string Describe { get; set; }

    }
}
