//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-07 14:41:24 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///SalePointFile info
    /// </summary>
    [Table("CT_SalePointFile")]
    public class SalePointFileEntity
    {

        /// <summary>
        /// 点位变更文件ID
        /// </summary>
        [Key]
        public long SalePointFileID { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 文件路径
        /// </summary>
        public string FileUrl { get; set; }

        /// <summary>
        /// 文件名
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// 文件后缀
        /// </summary>
        public string FileEXT { get; set; }

        /// <summary>
        /// 文件签名
        /// </summary>
        public long FileSign { get; set; }

    }
}
