//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///SchemesDetail info
    /// </summary>
    [Table("CT_SchemesDetail")]
    public class SchemesDetailEntity
    {

        /// <summary>
        /// 流水号
        /// </summary>
        [Key]
        public long SDID { get; set; }

        /// <summary>
        /// 订单号
        /// </summary>
        public long SchemeID { get; set; }

        /// <summary>
        /// 玩法编码
        /// </summary>
        public int PlayCode { get; set; }

        /// <summary>
        /// 倍数
        /// </summary>
        public int Multiple { get; set; }

        /// <summary>
        /// 注数
        /// </summary>
        public int BetNum { get; set; }

        /// <summary>
        /// 投注号码
        /// </summary>
        public string BetNumber { get; set; }

        /// <summary>
        /// 是否已出票 0未出票 1已出票
        /// </summary>
        public bool? IsBuyed { get; set; }

        /// <summary>
        /// 是否非胆拖操作
        /// </summary>
        public byte IsNorm { get; set; }

        /// <summary>
        /// 是否中奖
        /// </summary>
        public byte IsWin { get; set; }

        /// <summary>
        /// 是否开奖
        /// </summary>
        public bool IsOpened { get; set; }

        /// <summary>
        /// 奖金
        /// </summary>
        public long WinMoney { get; set; }

        /// <summary>
        /// 税后奖金
        /// </summary>
        public long WinMoneyNoWithTax { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int Schedule { get; set; }

        /// <summary>
        /// 中奖描述
        /// </summary>
        public string WinDescribe { get; set; }

        /// <summary>
        /// 出票时间
        /// </summary>
        public DateTime? PrintOutTime { get; set; }

        /// <summary>
        /// 中奖图片URL
        /// </summary>
        public string WinImageUrl { get; set; }

        /// <summary>
        /// 状态更新时间
        /// </summary>
        public DateTime UpdateTime { get; set; }

        /// <summary>
        /// 开奖操作员编号
        /// </summary>
        public int OpenOperatorID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public long BetMoney { set; get; }

    }
}
