//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///SchemeETickets info
    /// </summary>
    [Table("CT_SchemeETickets")]
    public class SchemeETicketsEntity
    {

        /// <summary>
        /// 电子票订单号
        /// </summary>
        [Key]
        public long SchemeETicketsID { get; set; }


        /// <summary>
        /// 出票平台:1.华阳
        /// </summary>
        public int TicketSourceID { get; set; }

        /// <summary>
        /// 发起时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 对应订单号
        /// </summary>
        public long SchemeID { get; set; }

        /// <summary>
        /// 发送失败重复次数
        /// </summary>
        public short Sends { get; set; }

        /// <summary>
        /// 操作时间
        /// </summary>
        public DateTime HandleDateTime { get; set; }

        /// <summary>
        /// 操作描述
        /// </summary>
        public string HandleDescribe { get; set; }

        /// <summary>
        /// 彩票标示码
        /// </summary>
        public string Identifiers { get; set; }

        /// <summary>
        /// 票据信息
        /// </summary>
        public string Ticket { get; set; }

        /// <summary>
        /// 奖金
        /// </summary>
        public long WinMoney { get; set; }

        /// <summary>
        /// 状态,0.待出票，1.投注成功，2.出票完成，3.投注失败，4.出票失败，8.兑奖中，10中奖，11.不中
        /// </summary>
        public byte TicketStatus { get; set; }

        /// <summary>
        /// 追号明细ID
        /// </summary>
        public long ChaseTaskDetailsID { get; set; }


        #region 调整增加的字段

        /// <summary>
        /// 方案详情标识列
        /// </summary>
        public long SDID { set; get; }

        /// <summary>
        /// 玩法编号
        /// </summary>
        public int PlayCode { set; get; }

        /// <summary>
        /// 电子票金额
        /// </summary>
        public long TicketMoney { set; get; }

        /// <summary>
        /// 投注倍数
        /// </summary>
        public int Multiple { set; get; }

        /// <summary>
        /// 投注内容
        /// </summary>
        public string Number { set; get; }
        #endregion

    }
}
