//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-09-08 15:26:16 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;

namespace CL.Game.Entity
{

    /// <summary>
    /// 加奖表记录
    /// </summary>
    [Table("CT_SchemesAwards")]
    public class SchemesAwardsEntity
    {

        /// <summary>
        /// 加奖表标识
        /// </summary>
        [Key]
        public long AwardsID { get; set; }

        /// <summary>
        /// 方案标识
        /// </summary>
        public long SchemeID { get; set; }

        /// <summary>
        /// 电子票标识
        /// </summary>
        public long SchemeETicketID { get; set; }

        /// <summary>
        /// 加奖规则标识
        /// </summary>
        public int RegularID { get; set; }

        /// <summary>
        /// 加奖类型：0 彩种官方加奖，1 彩乐加奖；
        /// </summary>
        public byte AwardType { get; set; }

        /// <summary>
        /// 加奖时间
        /// </summary>
        public DateTime AwardTime { get; set; }

        /// <summary>
        /// 加奖金额
        /// </summary>
        public long AwardMoney { get; set; }

        /// <summary>
        /// 加奖用户
        /// </summary>
        public long UserID { get; set; }

    }
}
