//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///SchemesDetailsWin info
    /// </summary>
    [Table("CT_SchemesWin")]
    public class SchemesWinEntity
    {

        /// <summary>
        /// 编号ID
        /// </summary>
        [Key]
        public long SchemesDetailsWinID { get; set; }

        /// <summary>
        /// 电子票ID
        /// </summary>
        public long SchemeETicketsID { get; set; }

        /// <summary>
        /// 方案ID
        /// </summary>
        public long SchemeID { get; set; }

        /// <summary>
        /// 方案发起者ID
        /// </summary>
        public long UserID { get; set; }

        /// <summary>
        /// 彩种编号
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 奖等编号
        /// </summary>
        public int WinCode { get; set; }

        /// <summary>
        /// 拆分号码
        /// </summary>
        public string SplitNumber { get; set; }

        /// <summary>
        /// 开奖号码
        /// </summary>
        public string WinNumber { get; set; }

        /// <summary>
        /// 投注倍数
        /// </summary>
        public int Multiple { get; set; }

        /// <summary>
        /// 中奖金额
        /// </summary>
        public long WinMoney { get; set; }

        /// <summary>
        /// 中奖税后金额
        /// </summary>
        public long WinMoneyNoWithTax { get; set; }

        /// <summary>
        /// 是否派奖 0.否 1.是
        /// </summary>
        public byte IsAward { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        public string Descriptions { get; set; }

        /// <summary>
        /// 返奖接口 1.华阳
        /// </summary>
        public int SupplierID { get; set; }

        /// <summary>
        /// 返奖金额
        /// </summary>
        public long BackWinMoney { get; set; }

        /// <summary>
        /// 返奖税后金额
        /// </summary>
        public long BackWinMoneyNoWithTax { get; set; }

        /// <summary>
        /// 返奖时间
        /// </summary>
        public DateTime? BackDateTime { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime? AddDateTime { get; set; }

        /// <summary>
        /// 派奖对比是否中奖 0.未中奖 1.中奖
        /// </summary>
        public byte WinStatus { get; set; }
        

        /// <summary>
        /// 是否手动派奖,使用于双色球、大乐透等 0.否 1.是
        /// </summary>
        public byte IsFirstPrize { get; set; }

    }
}
