//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///Schemes info
    /// </summary>
    [Table("CT_Schemes")]
    public class SchemesEntity
    {

        /// <summary>
        /// 
        /// </summary>
        [Key]
        public long SchemeID { get; set; }

        /// <summary>
        /// 发起时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 方案号
        /// </summary>
        public string SchemeNumber { get; set; }

        /// <summary>
        /// 方案标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 发起人编号
        /// </summary>
        public long InitiateUserID { get; set; }

        /// <summary>
        /// 玩法编号 规则，采取五位编码，三位彩种编号+两位序号，具体如下：新快三和值3,10101  新快三和值4,10102  新快三三同号,10117双色球机选一注,80101
        /// </summary>
        public int LotteryCode { get; set; }

        /// <summary>
        /// 期号流水号
        /// </summary>
        public long IsuseID { get; set; }

        /// <summary>
        /// 期号
        /// </summary>
        public string IsuseName { get; set; }

        /// <summary>
        /// 购买号码（具体数据格式如下：注与注之间用“|”分割，玩法与注之间用“-”分割，投注号码之间用“,”分割，红球与篮球之间用“+”分割,篮球与幸运蓝球用”(“分割，例如【10101-3|10113-15|10119-3,3,3|80101-1,2,3,5,6,7+5(2|90101-4,5,6,7,8+4,8】）
        /// </summary>
        public string LotteryNumber { get; set; }

        /// <summary>
        /// 方案总金额
        /// </summary>
        public long SchemeMoney { get; set; }

        /// <summary>
        /// 保密级别 0不保密 1 保密到截止 2保密到开奖 3永远保密
        /// </summary>
        public short SecrecyLevel { get; set; }

        /// <summary>
        /// 订单状态 0待付款，2.订单过期，4下单成功，6.出票成功，8.部分出票成功，10.下单失败（限号），12.订单撤销，14.中奖，15.派奖中，16.派奖完成，18.不中奖完成，19.追号进行中，20.追号完成
        /// </summary>
        public short SchemeStatus { get; set; }

        /// <summary>
        /// 出票方式 1本地出票 2电子票 3线下商家出票
        /// </summary>
        public byte PrintOutType { get; set; }

        /// <summary>
        /// 方案描述
        /// </summary>
        public string Describe { get; set; }

        /// <summary>
        /// 方案来源 1网页 2 IOS 3 Andiord
        /// </summary>
        public byte FromClient { get; set; }

        /// <summary>
        /// 购买类型 0.代购 1追号2.跟单
        /// </summary>
        public byte BuyType { get; set; }

        /// <summary>
        /// 方案是否拆分
        /// </summary>
        public bool IsSplit { get; set; }

        /// <summary>
        /// 跟单方案编号
        /// </summary>
        public long FollowSchemeID { get; set; }

        /// <summary>
        /// 复制跟单佣金
        /// </summary>
        public int FollowSchemeBonus { get; set; }

        /// <summary>
        /// 复制跟单佣金比例
        /// </summary>
        public int FollowSchemeBonusScale { get; set; }

        /// <summary>
        /// 加奖，特殊时候，会出现加奖的情况
        /// </summary>
        public int PlusAwards { get; set; }

        public string RoomCode { set; get; }

        public bool IsSendOut { set; get; }
    }
}
