//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///SystemSetInfo info
    /// </summary>
    [Table("CT_SystemSetInfo")]
    public class SystemSetInfoEntity
    {

        /// <summary>
        /// 配置流水号
        /// </summary>
        [Key]
        public int SetID { get; set; }

        /// <summary>
        /// 配置键
        /// </summary>
        public string SetKey { get; set; }

        /// <summary>
        /// 配置值
        /// </summary>
        public string SetValue { get; set; }

        /// <summary>
        /// 配置名
        /// </summary>
        public string SetName { get; set; }

        /// <summary>
        /// 配置描述
        /// </summary>
        public string SetDetail { get; set; }

        /// <summary>
        /// 排序号
        /// </summary>
        public int Sort { get; set; }

        /// <summary>
        /// 是否可用
        /// </summary>
        public byte IsUse { get; set; }

        /// <summary>
        /// 数据类型 0.string 1.int 2.checked 3.radio 4.url 5datetime 6.other
        /// </summary>
        public byte DataType { get; set; }

        /// <summary>
        /// 类型值(如checked、radio的值)
        /// </summary>
        public string DataValue { get; set; }

    }
}
