//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///TemplateConfig info
    /// </summary>
    [Table("CT_TemplateConfig")]
    public class TemplateConfigEntity
    {

        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public long ID { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 内容
        /// </summary>
        public string TemplateContent { get; set; }

        /// <summary>
        /// 消息类型 1.公告Announce 2.提醒Remind 3.私信Message 4.推送Push
        /// </summary>
        public byte TemplateType { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 管理员ID
        /// </summary>
        public int AdminID { get; set; }

    }
}
