//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///Users info
    /// </summary>
    [Table("CT_Users")]
    public class UsersEntity
    {

        /// <summary>
        /// 用户ID
        /// </summary>
        [Key]
        public long UserID { get; set; }

        /// <summary>
        /// 会员名
        /// </summary>
        public string UserName { get; set; } = string.Empty;

        /// <summary>
        /// 用户手机号码
        /// </summary>
        public string UserMobile { get; set; } = string.Empty;

        /// <summary>
        /// 用户密码
        /// </summary>
        public string UserPassword { get; set; } = string.Empty;

        /// <summary>
        /// 支付密码(6位数字后的MD5)
        /// </summary>
        public string PayPassword { get; set; } = string.Empty;

        /// <summary>
        /// 用户余额
        /// </summary>
        public long Balance { get; set; } = 0;

        /// <summary>
        /// 金豆与余额的兑换比例是1:100
        /// </summary>
        public long GoldBean { get; set; } = 0;

        /// <summary>
        /// 冻结金额
        /// </summary>
        public long Freeze { get; set; } = 0;

        /// <summary>
        /// 是否是机器人
        /// </summary>
        public bool IsRobot { get; set; } = false;

        /// <summary>
        /// 账户是否允许登陆
        /// </summary>
        public bool IsCanLogin { get; set; } = true;

    }
}
