//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///UsersBanks info
    /// </summary>
    [Table("CT_UsersBanks")]
    public class UsersBanksEntity
    {

        /// <summary>
        /// 银行编号
        /// </summary>
        [Key]
        public long BankID { get; set; }

        /// <summary>
        /// 用户编号
        /// </summary>
        public long UserID { get; set; }

        /// <summary>
        /// 银行类型  1工商银行 2建设银行 3农业银行 4交通银行 5招商银行 6邮政银行,100.微信，101.财付通，102.支付宝
        /// </summary>
        public short BankType { get; set; }

        /// <summary>
        /// 开户银行
        /// </summary>
        public string BankName { get; set; }

        /// <summary>
        /// 银行卡号
        /// </summary>
        public string CardNumber { get; set; }

        /// <summary>
        /// 地市
        /// </summary>
        public string Area { get; set; }

        /// <summary>
        /// 创建卡号的时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 预留电话号码
        /// </summary>
        public string ReservedPhone { get; set; }

    }
}
