//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:32 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///UsersWithdraw info
    /// </summary>
    [Table("CT_UsersWithdraw")]
    public class UsersWithdrawEntity
    {

        /// <summary>
        /// 流水号
        /// </summary>
        [Key]
        public long PayOutID { get; set; }

        /// <summary>
        /// 提现人编号
        /// </summary>
        public long UserID { get; set; }

        /// <summary>
        /// 金额
        /// </summary>
        public long Amount { get; set; }

        /// <summary>
        /// 银行编号
        /// </summary>
        public int BankID { get; set; }

        /// <summary>
        /// 申请时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 处理人编号
        /// </summary>
        public long? OperaterID { get; set; }

        /// <summary>
        /// 处理时间
        /// </summary>
        public DateTime? OperTime { get; set; }

        /// <summary>
        /// 状态，0.申请，2.处理中，4.处理完成，6.提现失败
        /// </summary>
        public byte PayOutStatus { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { set; get; }
    }
}
