//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///UsersLoginRecord info
    /// </summary>
    [Table("CT_UsersLoginRecord")]
    public class UsersLoginRecordEntity
    {

        /// <summary>
        /// 流水号
        /// </summary>
        [Key]
        public long ID { get; set; }

        /// <summary>
        /// 用户编号
        /// </summary>
        public long UserID { get; set; }

        /// <summary>
        /// 来源类型：0.pc，1.android，2.ios，3.ipad
        /// </summary>
        public byte SourceType { get; set; }

        /// <summary>
        /// 登陆码
        /// </summary>
        public string Token { get; set; }

        /// <summary>
        /// 登陆时间
        /// </summary>
        public DateTime LoginTime { get; set; }

        /// <summary>
        /// IP地址
        /// </summary>
        public string IpAddress { get; set; }

    }
}
