//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///UsersExtend info
    /// </summary>
    [Table("CT_UsersExtend")]
    public class UsersExtendEntity
    {

        /// <summary>
        /// 用户编号
        /// </summary>
        [Key]
        public long UserID { get; set; }

        /// <summary>
        /// 用户昵称
        /// </summary>
        public string NickName { get; set; } = string.Empty;

        /// <summary>
        /// 用户级别
        /// </summary>
        public byte UserLevel { get; set; } = 0;

        /// <summary>
        /// 特殊等级(例如百万中奖户)
        /// </summary>
        public byte SpecialLevel { get; set; } = 0;

        /// <summary>
        /// 姓名
        /// </summary>
        public string FullName { get; set; } = string.Empty;

        /// <summary>
        /// 身份证号码
        /// </summary>
        public string IDNumber { get; set; } = string.Empty;

        /// <summary>
        /// 用户头像地址
        /// </summary>
        public string AvatarAddress { get; set; } = string.Empty;

        /// <summary>
        /// 微信唯一标示
        /// </summary>
        public string WechatID { get; set; } = string.Empty;

        /// <summary>
        /// 微信票据
        /// </summary>
        public string WechatToken { get; set; } = string.Empty;

        /// <summary>
        /// 支付宝标识
        /// </summary>
        public string AliPayID { get; set; } = string.Empty;

        /// <summary>
        /// 支付宝票据
        /// </summary>
        public string AliPayToken { get; set; } = string.Empty;

        /// <summary>
        /// QQ编号
        /// </summary>
        public string QQID { get; set; } = string.Empty;

        /// <summary>
        /// QQ票据
        /// </summary>
        public string QQToken { get; set; } = string.Empty;

        /// <summary>
        /// 邮件
        /// </summary>
        public string Email { get; set; } = string.Empty;

        /// <summary>
        /// 绑定类型，0.未绑定，1.手机，2.微信，3.QQ，4.支付宝
        /// </summary>
        public byte? BindType { get; set; } = 0;

        /// <summary>
        /// 注册时间
        /// </summary>
        public DateTime? CreateTime { get; set; } = DateTime.Now;

        /// <summary>
        /// 绑定时间
        /// </summary>
        public DateTime? BindTime { get; set; } = DateTime.Now;

        /// <summary>
        /// 关注数
        /// </summary>
        public int? Idols { get; set; } = 0;

        /// <summary>
        /// 来源类型：0.pc，1.android，2.ios，3.ipad
        /// </summary>
        public byte? SourceType { get; set; } = 1;

        /// <summary>
        /// IP地址
        /// </summary>
        public string IpAddress { get; set; } = string.Empty;

        /// <summary>
        /// 第三方关联id
        /// </summary>
        public string RelationID { get; set; } = string.Empty;

        /// <summary>
        /// 是否认证通过
        /// </summary>
        public bool? IsVerify { get; set; } = false;

        /// <summary>
        /// 是否绑定手机
        /// </summary>
        public bool? IsBindTel { get; set; } = false;
        /// <summary>
        /// 可提现金额(充值百分之五十可提现)
        /// </summary>
        public long WithdrawMoney { set; get; } = 0;

    }
}
