//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:31 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///UsersStaticdata info
    /// </summary>
    [Table("CT_UsersStaticdata")]
    public class UsersStaticdataEntity
    {

        /// <summary>
        /// 日期 格式20170101
        /// </summary>
        public int Date { get; set; }

        /// <summary>
        /// 用户ID
        /// </summary>
        public long UserID { get; set; }

        /// <summary>
        /// 购买总额
        /// </summary>
        public long Buy { get; set; }

        /// <summary>
        /// 中奖总额
        /// </summary>
        public long Win { get; set; }

    }
}
