//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:45:32 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper;
namespace CL.Game.Entity
{

    /// <summary>
    ///WinTypes info
    /// </summary>
    [Table("CT_WinTypes")]
    public class WinTypesEntity
    {

        /// <summary>
        /// 奖等流水号
        /// </summary>
        [Key]
        public int WinID { get; set; }

        /// <summary>
        /// 奖等编码，五位关联编码+两位自编码
        /// </summary>
        public int? WinCode { get; set; }

        /// <summary>
        /// 彩种编码
        /// </summary>
        public int? LotteryCode { get; set; }

        /// <summary>
        /// 玩法编码规则，采用三位彩种编码+两位自编码，如新快三的【和值】10101，三同号10102
        /// </summary>
        public int? PlayCode { get; set; }

        /// <summary>
        /// 奖等名称
        /// </summary>
        public string WinName { get; set; }

        /// <summary>
        /// 中奖号码，列出所有符合中奖的号码
        /// </summary>
        public string WinNumber { get; set; }

        /// <summary>
        /// 是否和值
        /// </summary>
        public byte? IsSumValue { get; set; }

        /// <summary>
        /// 和值数
        /// </summary>
        public int? SumValue { get; set; }

        /// <summary>
        /// 排序号
        /// </summary>
        public int? Sort { get; set; }

        /// <summary>
        /// 默认奖金
        /// </summary>
        public int? DefaultMoney { get; set; }

        /// <summary>
        /// 默认税后奖金
        /// </summary>
        public int? DefaultMoneyNoWithTax { get; set; }
        

    }
}
