//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:41:09 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper;
namespace CL.SystemInfo.Entity
{

    /// <summary>
    ///ErrorLog info
    /// </summary>
    [Table("CT_ErrorLog")]
    public class ErrorLogEntity
    {

        /// <summary>
        /// 错误日志流水号
        /// </summary>
        [Key]
        public int ID { get; set; }

        /// <summary>
        /// 方法描述
        /// </summary>
        public string MethedDescribe { get; set; }

        /// <summary>
        /// 方法名称
        /// </summary>
        public string MethedName { get; set; }

        /// <summary>
        /// 操作参数
        /// </summary>
        public string OperateParamters { get; set; }

        /// <summary>
        /// 错误内容
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// 错误详情
        /// </summary>
        public string StackTrace { get; set; }

        /// <summary>
        /// 记录时间
        /// </summary>
        public DateTime? RecordTime { get; set; }

    }
}
