//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     2017-04-25 20:41:10 Created by LEON
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper;
using System.Collections.Generic;

namespace CL.SystemInfo.Entity
{

    /// <summary>
    ///Rosle info
    /// </summary>
    [Table("CT_Rosle")]
    public class RosleEntity
    {
        [Key]
        /// <summary>
        /// 
        /// </summary>
        public int RoleID { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string RoleName { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public byte RoleType { get; set; }

        /// <summary>
        /// 权限子类 
        /// </summary>
        public List<RosleValueEntity> manager_role_values { get; set; }

    }
}
